#### **IMPORTANDO LIBRERÍA NUMPY**

In [1]:
import numpy as np

##### Creando una lista de 10 Elementos

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [4]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [5]:
arreglo.dtype

dtype('int32')

##### Definiendo el Array de int32 a float32


In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [9]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [10]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [11]:
promedio = np.mean(arreglo)
promedio

5.5

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [12]:
mediana = np.median(arreglo)
mediana

5.5

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [13]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [14]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [15]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [16]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos </h4>



In [17]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.4200975 , 0.60124524, 0.6832534 , 0.32066824, 0.75633538,
       0.49763152, 0.02581912, 0.0034357 , 0.02602051, 0.84001886])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [18]:
matriz = np.random.rand(3,3)
matriz

array([[0.77260972, 0.10355   , 0.23689003],
       [0.70589347, 0.83545014, 0.43805584],
       [0.29140073, 0.83385126, 0.3149823 ]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [19]:
arreglo_aleatorio2  = np.random.randint(1,1001,5)
arreglo_aleatorio2

array([554, 576, 872, 851,  83])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [20]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[29, 56, 16, 45, 87, 58, 15, 68, 78, 95],
       [94, 13, 78, 57, 18,  9, 82, 19, 80, 90],
       [34, 90, 30, 72, 70, 11, 26, 92, 54, 53],
       [84, 83, 30, 84, 38, 29,  4, 43, 73, 69],
       [ 4, 91, 33,  2, 26, 31, 49, 23, 14, 11],
       [52, 89, 77, 43, 70,  3, 37,  7, 44, 18],
       [49, 95, 59, 54, 95, 68, 29, 67, 30, 82],
       [67, 41, 79, 13, 99, 50, 37, 53, 35, 32],
       [65, 29, 76, 67, 24, 92, 82, 80,  1, 94],
       [ 4, 18, 31, 74, 77, 72, 97, 93, 57, 68]])